routes:
  - type: rewrite
    source: /*
    destination: /index.html

services:
  - type: web
    name: cit-forums-ui
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
